// ─────────────────────────────────────────────────────────────
//  THE 24 TIRTHANKARAS
//  Standard Shvetambar tradition details. Verify locally before
//  treating as authoritative — minor details vary by source.
// ─────────────────────────────────────────────────────────────
const TIRTHANKARAS = [
{n:1,name:'Rishabhanath (Adinath)',sanskrit:'ऋषभनाथ (आदिनाथ)',lanchan:'Bull',color:'Golden',father:'King Nabhi',mother:'Marudevi',birthplace:'Ayodhya',moksha:'Ashtapad (Mount Kailash)',
fact:'The first Tirthankara of this era. He taught humanity agriculture, arts, writing and social order before renouncing. His year-long fast was broken with sugarcane juice on Akshaya Tritiya. Father of Bharat (after whom India is named "Bharatvarsh") and Bahubali.'},
{n:2,name:'Ajitanath',sanskrit:'अजितनाथ',lanchan:'Elephant',color:'Golden',father:'King Jitashatru',mother:'Vijaya Devi',birthplace:'Ayodhya',moksha:'Sammed Shikhar',
fact:'His name means "the unconquered one" — while he was in the womb, his father could not be defeated by anyone.'},
{n:3,name:'Sambhavanath',sanskrit:'संभवनाथ',lanchan:'Horse',color:'Golden',father:'King Jitari',mother:'Sena Devi',birthplace:'Shravasti',moksha:'Sammed Shikhar',
fact:'Born during a great famine which ended with his birth — his name comes from "sambhav" (possibility/prosperity arising).'},
{n:4,name:'Abhinandananath',sanskrit:'अभिनंदननाथ',lanchan:'Monkey',color:'Golden',father:'King Samvara',mother:'Siddhartha Devi',birthplace:'Ayodhya',moksha:'Sammed Shikhar',
fact:'His name means "joy and felicitation" — the kingdom rejoiced throughout his mother\'s pregnancy.'},
{n:5,name:'Sumatinath',sanskrit:'सुमतिनाथ',lanchan:'Curlew (Krauncha bird)',color:'Golden',father:'King Megha',mother:'Mangala Devi',birthplace:'Ayodhya',moksha:'Sammed Shikhar',
fact:'His name means "wise one" — while he was in the womb his mother gained extraordinary wisdom, famously resolving a dispute between two women claiming the same child.'},
{n:6,name:'Padmaprabha',sanskrit:'पद्मप्रभ',lanchan:'Red Lotus',color:'Red',father:'King Shridhara',mother:'Susima Devi',birthplace:'Kaushambi',moksha:'Sammed Shikhar',
fact:'His name means "radiant as a lotus" — his mother craved a couch of red lotuses during pregnancy, and his complexion was lotus-red.'},
{n:7,name:'Suparshvanath',sanskrit:'सुपार्श्वनाथ',lanchan:'Swastika',color:'Golden',father:'King Pratishtha',mother:'Prithvi Devi',birthplace:'Varanasi',moksha:'Sammed Shikhar',
fact:'His name means "good-sided" — his mother\'s sides, afflicted before his conception, became beautiful and healthy.'},
{n:8,name:'Chandraprabha',sanskrit:'चंद्रप्रभ',lanchan:'Crescent Moon',color:'White',father:'King Mahasena',mother:'Lakshmana Devi',birthplace:'Chandrapuri',moksha:'Sammed Shikhar',
fact:'His name means "radiant as the moon" — his mother craved to drink moonlight during pregnancy, and his complexion was moon-white.'},
{n:9,name:'Pushpadanta (Suvidhinath)',sanskrit:'पुष्पदंत (सुविधिनाथ)',lanchan:'Crocodile (Makara)',color:'White',father:'King Sugriva',mother:'Rama Devi',birthplace:'Kakandi',moksha:'Sammed Shikhar',
fact:'Known by two names: Suvidhinath ("master of right procedures") and Pushpadanta ("flower-toothed", for teeth white as jasmine buds).'},
{n:10,name:'Shitalanath',sanskrit:'शीतलनाथ',lanchan:'Shrivatsa (Kalpavriksha)',color:'Golden',father:'King Dridharatha',mother:'Nanda Devi',birthplace:'Bhaddilpur',moksha:'Sammed Shikhar',
fact:'His name means "the cool one" — his touch cured his father\'s burning fever while he was still in the womb.'},
{n:11,name:'Shreyansanath',sanskrit:'श्रेयांसनाथ',lanchan:'Rhinoceros',color:'Golden',father:'King Vishnu',mother:'Vishna Devi',birthplace:'Simhapuri',moksha:'Sammed Shikhar',
fact:'His name means "beneficial to all". In a previous association, it was Prince Shreyans who first offered Adinath sugarcane juice, beginning the tradition of supatra-daan.'},
{n:12,name:'Vasupujya',sanskrit:'वासुपूज्य',lanchan:'Buffalo',color:'Red',father:'King Vasupujya',mother:'Jaya Devi',birthplace:'Champapuri',moksha:'Champapuri',
fact:'One of the few Tirthankaras who attained moksha somewhere other than Sammed Shikhar — all five of his kalyanaks happened at Champapuri. He never married or ruled.'},
{n:13,name:'Vimalanath',sanskrit:'विमलनाथ',lanchan:'Boar',color:'Golden',father:'King Kritavarma',mother:'Shyama Devi',birthplace:'Kampilya',moksha:'Sammed Shikhar',
fact:'His name means "the stainless one" — minds and hearts of people became pure (vimal) during his mother\'s pregnancy.'},
{n:14,name:'Anantanath',sanskrit:'अनंतनाथ',lanchan:'Falcon (Bear in Digambar tradition)',color:'Golden',father:'King Simhasena',mother:'Suyasha Devi',birthplace:'Ayodhya',moksha:'Sammed Shikhar',
fact:'His name means "the infinite one" — his father defeated an unconquerable ("ananta") enemy army while he was in the womb.'},
{n:15,name:'Dharmanath',sanskrit:'धर्मनाथ',lanchan:'Vajra (Thunderbolt)',color:'Golden',father:'King Bhanu',mother:'Suvrata Devi',birthplace:'Ratnapuri',moksha:'Sammed Shikhar',
fact:'His name means "lord of dharma" — his mother became exceptionally devoted to religious duties during pregnancy.'},
{n:16,name:'Shantinath',sanskrit:'शांतिनाथ',lanchan:'Deer',color:'Golden',father:'King Vishvasena',mother:'Achira Devi',birthplace:'Hastinapur',moksha:'Sammed Shikhar',
fact:'His name means "lord of peace" — his birth ended a deadly epidemic. He was also a Chakravarti (universal emperor) before renouncing, one of only a few souls to hold both posts.'},
{n:17,name:'Kunthunath',sanskrit:'कुंथुनाथ',lanchan:'Goat',color:'Golden',father:'King Sura',mother:'Shri Devi',birthplace:'Hastinapur',moksha:'Sammed Shikhar',
fact:'Also a Chakravarti before becoming a Tirthankara. His name relates to a heap of jewels ("kunthu") his mother saw in a dream.'},
{n:18,name:'Aranath',sanskrit:'अरनाथ',lanchan:'Nandyavarta (Fish in Digambar tradition)',color:'Golden',father:'King Sudarshana',mother:'Devi Rani',birthplace:'Hastinapur',moksha:'Sammed Shikhar',
fact:'The third consecutive Tirthankara born in Hastinapur, and also a Chakravarti. His mother dreamed of a jewelled wheel ("ara" = spoke).'},
{n:19,name:'Mallinath',sanskrit:'मल्लिनाथ',lanchan:'Kalasha (Water pot)',color:'Blue',father:'King Kumbha',mother:'Prabhavati Devi',birthplace:'Mithila',moksha:'Sammed Shikhar',
fact:'In the Shvetambar tradition, Mallinath was a woman — the only female Tirthankara — born a princess of extraordinary beauty who renounced the same day six kings came seeking her hand.'},
{n:20,name:'Munisuvrata',sanskrit:'मुनिसुव्रत',lanchan:'Tortoise',color:'Black',father:'King Sumitra',mother:'Padmavati Devi',birthplace:'Rajgrihi (Rajgir)',moksha:'Sammed Shikhar',
fact:'The Tirthankara of Lord Rama\'s era — the events of the Jain Ramayana took place during his tirtha. His name means "excellent in vows".'},
{n:21,name:'Naminath',sanskrit:'नमिनाथ',lanchan:'Blue Lotus',color:'Golden',father:'King Vijaya',mother:'Vapra Devi',birthplace:'Mithila',moksha:'Sammed Shikhar',
fact:'His name means "the one to whom all bow" — enemy kings besieging Mithila bowed in submission while he was in the womb.'},
{n:22,name:'Neminath (Arishtanemi)',sanskrit:'नेमिनाथ (अरिष्टनेमि)',lanchan:'Conch (Shankha)',color:'Black',father:'King Samudravijaya',mother:'Shivadevi',birthplace:'Sauripur',moksha:'Girnar',
fact:'Cousin of Lord Krishna. On his wedding day he heard the cries of animals to be slaughtered for the feast, turned his chariot around, and renounced the world — his bride Rajimati followed him into renunciation. He attained moksha on Mount Girnar.'},
{n:23,name:'Parshvanath',sanskrit:'पार्श्वनाथ',lanchan:'Serpent',color:'Blue',father:'King Ashvasena',mother:'Vamadevi',birthplace:'Varanasi',moksha:'Sammed Shikhar',
fact:'A historical figure (c. 877–777 BCE). As a prince he saved a serpent burning in a tapas fire — that soul became Dharanendra, who sheltered him with a thousand-hooded canopy during Kamath\'s deadly storm. Worshipped as Chintamani, Shankheshwar, and many other forms.'},
{n:24,name:'Mahavir (Vardhamana)',sanskrit:'महावीर (वर्धमान)',lanchan:'Lion',color:'Golden',father:'King Siddhartha',mother:'Trishala Devi',birthplace:'Kshatriyakund (Vaishali)',moksha:'Pavapuri',
fact:'The last Tirthankara (599–527 BCE). Born Vardhamana ("ever-growing"), he renounced at 30, practiced severe austerities for 12½ years, attained Kevalgyan, and taught for 30 years. His first disciple was Gautam Swami. He attained nirvana at Pavapuri on Diwali night.'},
]; // end TIRTHANKARAS
